(async()=>{try{const key="tiffas-cache-reset-v8";if(sessionStorage.getItem(key)!=="1"){sessionStorage.setItem(key,"1");let changed=false;if("serviceWorker" in navigator){const regs=await navigator.serviceWorker.getRegistrations();for(const reg of regs){changed=await reg.unregister()||changed;}}if("caches" in window){const keys=await caches.keys();if(keys.length){await Promise.all(keys.map(k=>caches.delete(k)));changed=true;}}if(changed){const u=new URL(location.href);u.searchParams.set("_tiffas_refresh",Date.now());location.replace(u.href);return;}}}catch(e){console.warn("TIFFAS cache reset skipped",e)}})();
document.addEventListener("DOMContentLoaded", () => {
  const C = window.TIFFAS_CONFIG || {};
  const STORE_NAME = C.STORE_NAME || "TIFFAS BEAUTY AND COSMETICS";
  const WHATSAPP = C.WHATSAPP_NUMBER || "254725679016";
  const CATALOG_URL = C.CATALOG_URL || "catalog/products.json";
  const SETTINGS_URL = C.SETTINGS_URL || "store-settings.json";
  let products = [];
  let settings = {whatsappNumber:WHATSAPP,bankName:"",accountName:STORE_NAME,accountNumber:"",branch:"",swiftCode:"",paymentInstructions:"Use your order number as the transfer reference, then send proof of payment by WhatsApp.",currency:"KES"};
  let category="All", query="", cart=[];
  try{cart=JSON.parse(localStorage.getItem("tiffas_cart")||"[]");if(!Array.isArray(cart))cart=[];}catch(_){cart=[];}
  const $=id=>document.getElementById(id);
  const money=n=>`Ksh ${Number(n||0).toLocaleString("en-KE")}`;
  const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
  const wa=text=>`https://wa.me/${settings.whatsappNumber||WHATSAPP}?text=${encodeURIComponent(text)}`;
  const saveCart=()=>{try{localStorage.setItem("tiffas_cart",JSON.stringify(cart));}catch(_){}};
  const subtotal=()=>cart.reduce((sum,i)=>sum+Number(i.price||0)*Number(i.qty||0),0);
  if(["search","categories","count","grid","empty","cartItems","subtotal","cartBadge"].some(id=>!$(id)))return;
  const assetVersion=Date.now();
  function resolveAsset(p){if(!p)return"";if(/^(https?:|data:|blob:)/i.test(p))return p;const u=new URL(p.replace(/^\//,""),document.baseURI);u.searchParams.set("v",assetVersion);return u.href;}
  function toast(msg){const el=$("toast");if(!el)return;el.textContent=msg;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,2400);}
  function needsCustomerChoice(p){return /jibambe|avis|asad|body\s*spray/i.test(String(p&&p.name||""));}
  function choicePrompt(p){var n=String(p&&p.name||"");return /jibambe|avis/i.test(n)?"Which braid / colour / number do you want?":"Which fragrance / variant / size do you want?";}
  function choicePlaceholder(p){var n=String(p&&p.name||"");return /jibambe|avis/i.test(n)?"e.g. 1, 1B, 27, 33, 1/27, etc.":"e.g. fragrance, size or variant";}
  function card(p){    var primary=p.image?resolveAsset(p.image):"";    var fallback=p.fallbackImage?resolveAsset(p.fallbackImage):"";    var img=primary?"<img src=\"" + esc(primary) + "\" data-fallback=\"" + esc(fallback) + "\" alt=\"" + esc(p.name) + "\" loading=\"lazy\" onerror=\"if(this.dataset.fallback&&!this.dataset.triedFallback){this.dataset.triedFallback=\'1\';this.src=this.dataset.fallback;}else{this.style.display=\'none\';this.nextElementSibling.style.display=\'grid\';}\"><span class=\"placeholder\" style=\"display:none\">" + esc((p.name||"B").charAt(0)) + "</span>" : "<span class=\"placeholder\">" + esc((p.name||"B").charAt(0)) + "</span>";    var add=(p.price!=null&&p.inStock!==false)?"<button class=\"add\" data-add=\"" + esc(p.id) + "\">Add</button>":"<button class=\"add\" disabled>Out of stock</button>";    var description=p.description?"<p class=\"product-description\">" + esc(p.description) + "</p>":"";    var requestField=needsCustomerChoice(p)?"<label class=\"product-request\"><span>" + esc(choicePrompt(p)) + "</span><input type=\"text\" data-request placeholder=\"" + esc(choicePlaceholder(p)) + "\" autocomplete=\"off\"></label>":"";    return "<article class=\"card\"><div class=\"card-media\">" + img + "</div><div class=\"card-body\"><small>" + esc(p.category||"Beauty & Cosmetics") + "</small><h3>" + esc(p.name) + "</h3>" + description + requestField + "<strong>" + (p.price==null?"Price on request":money(p.price)) + "</strong><div class=\"card-actions\"><a class=\"mini-wa\" href=\"" + wa("Hi " + STORE_NAME + "! I would like to order " + p.name + ".") + "\" target=\"_blank\" rel=\"noopener\">WhatsApp</a>" + add + "</div></div></article>";  }
  function render(){const term=query.trim().toLowerCase();const list=products.filter(p=>(category==="All"||p.category===category)&&(!term||String(p.name||"").toLowerCase().includes(term)||String(p.category||"").toLowerCase().includes(term)));$("count").textContent=`Showing ${list.length} of ${products.length} products`;$("grid").innerHTML=list.map(card).join("");$("empty").hidden=list.length!==0;}
  function categories(){const cats=["All",...new Set(products.map(p=>p.category).filter(Boolean))];$("categories").innerHTML=cats.map(c=>`<button type="button" class="pill ${c===category?"active":""}" data-cat="${esc(c)}">${esc(c)}</button>`).join("");}
  function renderCart(){$("cartBadge").hidden=cart.length===0;$("cartBadge").textContent=String(cart.reduce((s,i)=>s+Number(i.qty||0),0));$("subtotal").textContent=money(subtotal());$("cartItems").innerHTML=cart.length?cart.map(function(i){return "<div class=\"cart-item\"><div><b>"+esc(i.name)+"</b>"+(i.request?"<small>Request: "+esc(i.request)+"</small>":"")+"<small>"+money(i.price)+" × "+i.qty+"</small></div><div class=\"qty\"><button type=\"button\" data-dec=\""+esc(i.key||i.id)+"\">−</button><span>"+i.qty+"</span><button type=\"button\" data-inc=\""+esc(i.key||i.id)+"\">+</button></div></div>";}).join(""):"<div class=\"empty\">Your cart is empty.</div>";}
  function openCart(){$("cartDrawer")?.classList.add("open");if($("drawerOverlay"))$("drawerOverlay").hidden=false;renderCart();}
  function closeCart(){$("cartDrawer")?.classList.remove("open");if($("drawerOverlay"))$("drawerOverlay").hidden=true;}
  function orderNumber(){const d=new Date(),p=n=>String(n).padStart(2,"0");return"TIF"+d.getFullYear()+p(d.getMonth()+1)+p(d.getDate())+p(d.getHours())+p(d.getMinutes())+p(d.getSeconds());}
  function bankDetailsHtml(ref){const rows=[["Bank",settings.bankName],["Account name",settings.accountName],["Account number",settings.accountNumber],["Branch",settings.branch],["SWIFT / BIC",settings.swiftCode]].filter(([,v])=>v);return`<div class="bank-details">${rows.map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join("")||"<p>Bank details have not been configured yet. Please contact TIFFAS on WhatsApp.</p>"}<div><span>Order reference</span><b>${esc(ref)}</b></div></div>`;}
  function openCheckout(){if(!cart.length)return toast("Your cart is empty.");const ref=orderNumber();$("modalOverlay").hidden=false;$("modalContent").innerHTML=`<h2 id="modalTitle">Bank transfer checkout</h2><p>Total to transfer: <b>${money(subtotal())}</b></p>${bankDetailsHtml(ref)}<p class="hint">${esc(settings.paymentInstructions||"")}</p><div class="order-summary">${cart.map(i=>`<div><span>${esc(i.name)} × ${i.qty}${i.request?" — "+esc(i.request):""}</span><b>${money(Number(i.price||0)*Number(i.qty||0))}</b></div>`).join("")}</div><div class="actions-stack"><button id="copyBankModal" type="button" class="btn light full">Copy bank &amp; order details</button><button id="sendTransferOrder" type="button" class="btn whatsapp full">Send order on WhatsApp</button></div>`;$("copyBankModal").onclick=async()=>{const text=[`Order reference: ${ref}`,`Total: ${money(subtotal())}`,settings.bankName?`Bank: ${settings.bankName}`:"",settings.accountName?`Account name: ${settings.accountName}`:"",settings.accountNumber?`Account number: ${settings.accountNumber}`:"",settings.branch?`Branch: ${settings.branch}`:"",settings.swiftCode?`SWIFT/BIC: ${settings.swiftCode}`:""].filter(Boolean).join("\n");try{await navigator.clipboard.writeText(text);toast("Bank details copied");}catch(_){toast("Copy failed; use the details shown above.");}};$("sendTransferOrder").onclick=()=>{const msg=`Hi ${STORE_NAME}! I want to place order ${ref}.\n\n${cart.map(i=>`• ${i.name} × ${i.qty}${i.request?" — "+i.request:""} — ${money(i.price*i.qty)}`).join("\n")}\n\nTotal: ${money(subtotal())}\n\nI will pay by bank transfer using reference ${ref}.`;window.open(wa(msg),"_blank","noopener");};}
  function closeModal(){if($("modalOverlay"))$("modalOverlay").hidden=true;}
  function cartMessage(){return`Hi ${STORE_NAME}! I'd like to order:\n\n${cart.map(i=>`• ${i.name} × ${i.qty} — ${money(i.price*i.qty)}`).join("\n")}\n\nTotal: ${money(subtotal())}`;}
  $("search").addEventListener("input",e=>{query=e.target.value;render();});
  $("categories").addEventListener("click",e=>{const b=e.target.closest("[data-cat]");if(!b)return;category=b.dataset.cat;categories();render();});
  $("grid").addEventListener("click",e=>{const b=e.target.closest("[data-add]");if(!b||b.disabled)return;const p=products.find(x=>String(x.id)===String(b.dataset.add));if(!p)return;const cardEl=b.closest(".card");const field=cardEl&&cardEl.querySelector("[data-request]");const request=field?field.value.trim():"";if(needsCustomerChoice(p)&&!request){if(field)field.focus();toast("Please tell us which braid, fragrance or variant you want.");return;}const key=String(p.id)+"|"+request.toLowerCase();const i=cart.find(x=>String(x.key||x.id)===key);i?i.qty++:cart.push({key:key,id:p.id,name:p.name,price:p.price,qty:1,request:request});saveCart();renderCart();if(field)field.value="";toast("Added to cart");});
  $("cartItems").addEventListener("click",e=>{const inc=e.target.closest("[data-inc]"),dec=e.target.closest("[data-dec]"),key=(inc||dec)?.dataset[inc?"inc":"dec"];if(!key)return;const i=cart.find(x=>String(x.key||x.id)===String(key));if(!i)return;i.qty+=inc?1:-1;if(i.qty<1)cart=cart.filter(x=>String(x.key||x.id)!==String(key));saveCart();renderCart();});
  $("cartOpen")?.addEventListener("click",openCart);$("cartClose")?.addEventListener("click",closeCart);$("drawerOverlay")?.addEventListener("click",closeCart);$("checkout")?.addEventListener("click",()=>{closeCart();openCheckout();});$("modalClose")?.addEventListener("click",closeModal);$("modalOverlay")?.addEventListener("click",e=>{if(e.target===$("modalOverlay"))closeModal();});$("cartWhatsapp")?.addEventListener("click",()=>window.open(wa(cartMessage()),"_blank","noopener"));
  $("copyBank")?.addEventListener("click",async()=>{const text=[settings.bankName,settings.accountName,settings.accountNumber,settings.branch].filter(Boolean).join("\n");if(!text)return toast("Bank details are not configured yet.");try{await navigator.clipboard.writeText(text);toast("Bank details copied");}catch(_){toast("Copy failed; use checkout to view details.");}});
  ["topWhatsapp","heroWhatsapp","footerWhatsapp"].forEach(id=>{const el=$(id);if(el){el.href=wa(`Hi ${STORE_NAME}! I'd like to know more about your products.`);if(id==="footerWhatsapp")el.textContent="0725 679 016";}});
  function updateBankSummary(){$("bankHeroName").textContent=settings.bankName||"Bank transfer";$("bankHeroAccount").textContent=settings.accountNumber||"Set in Admin";$("bankStripName").textContent=settings.bankName?`${settings.bankName} • ${settings.accountName||""}`:"Payment details available at checkout";$("bankFooter").textContent=settings.bankName?`${settings.bankName} • A/C ${settings.accountNumber||"available at checkout"}`:"Bank transfer details available at checkout";}
  const cacheBust=Date.now();Promise.all([fetch(CATALOG_URL+"?v="+cacheBust,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("Catalogue unavailable");return r.json();}),fetch(SETTINGS_URL+"?v="+cacheBust,{cache:"no-store"}).then(r=>r.ok?r.json():settings).catch(()=>settings)]).then(([items,store])=>{products=Array.isArray(items)?items:[];settings={...settings,...(store||{})};categories();render();renderCart();updateBankSummary();}).catch(e=>{console.error(e);$("count").textContent="Catalogue unavailable";$("grid").innerHTML="<div class='empty'>The catalogue could not be loaded. Please refresh the page.</div>";$("empty").hidden=true;updateBankSummary();});
});