window.TIFFAS_CONFIG = {
  WHATSAPP_NUMBER: "254725679016",
  STORE_NAME: "TIFFAS BEAUTY AND COSMETICS",
  CURRENCY: "KES",
  CATALOG_URL: "catalog/products.json",
  SETTINGS_URL: "store-settings.json"
};