require("dotenv").config();
const express=require("express");const cors=require("cors");const axios=require("axios");
const app=express();app.use(express.json());
app.use(cors({origin:(origin,cb)=>{if(!origin||/^https:\/\/[a-z0-9-]+\.github\.io$/.test(origin)||/^https:\/\/[a-z0-9-]+\.onrender\.com$/.test(origin)||origin.startsWith("http://localhost")||origin.startsWith("http://127.0.0.1"))return cb(null,true);cb(new Error("CORS blocked"));}}));
const KEY=process.env.MPESA_CONSUMER_KEY,SECRET=process.env.MPESA_CONSUMER_SECRET,SHORTCODE=process.env.MPESA_SHORTCODE||"8049446",PASSKEY=process.env.MPESA_PASSKEY,CALLBACK=process.env.MPESA_CALLBACK_URL,ENV=process.env.MPESA_ENV||"sandbox",TRANSACTION_TYPE=process.env.MPESA_TRANSACTION_TYPE||"CustomerBuyGoodsOnline",PORT=process.env.PORT||3000;
const BASE=ENV==="production"?"https://api.safaricom.co.ke":"https://sandbox.safaricom.co.ke";const payments=new Map();
app.get("/",(_q,r)=>r.json({ok:true,service:"tiffas-backend",environment:ENV,mpesaConfigured:!!(KEY&&SECRET&&PASSKEY&&CALLBACK)}));
app.get("/api/mpesa/config",(_q,r)=>r.json({configured:{consumerKey:!!KEY,consumerSecret:!!SECRET,passkey:!!PASSKEY,callbackUrl:!!CALLBACK,shortcode:!!SHORTCODE},environment:ENV,transactionType:TRANSACTION_TYPE,callbackUrl:CALLBACK?"configured":"missing"}));
async function token(){const a=Buffer.from(`${KEY}:${SECRET}`).toString("base64");const r=await axios.get(`${BASE}/oauth/v1/generate?grant_type=client_credentials`,{headers:{Authorization:`Basic ${a}`}});return r.data.access_token}
function stamp(){const d=new Date(),p=n=>String(n).padStart(2,"0");return d.getFullYear()+p(d.getMonth()+1)+p(d.getDate())+p(d.getHours())+p(d.getMinutes())+p(d.getSeconds())}
app.post("/api/mpesa/stkpush",async(req,res)=>{const {phone,amount,accountReference="TIFFAS",transactionDesc="Beauty order"}=req.body;if(!phone||!amount)return res.status(400).json({success:false,message:"phone and amount are required"});if(!KEY||!SECRET||!PASSKEY||!CALLBACK)return res.status(500).json({success:false,message:"M-Pesa environment variables are not configured on Render",missing:{consumerKey:!KEY,consumerSecret:!SECRET,passkey:!PASSKEY,callbackUrl:!CALLBACK}});try{const t=stamp(),pwd=Buffer.from(`${SHORTCODE}${PASSKEY}${t}`).toString("base64"),payload={BusinessShortCode:SHORTCODE,Password:pwd,Timestamp:t,TransactionType:TRANSACTION_TYPE,Amount:Math.round(amount),PartyA:phone,PartyB:SHORTCODE,PhoneNumber:phone,CallBackURL:CALLBACK,AccountReference:String(accountReference).slice(0,12),TransactionDesc:String(transactionDesc).slice(0,13)};const r=await axios.post(`${BASE}/mpesa/stkpush/v1/processrequest`,payload,{headers:{Authorization:`Bearer ${await token()}`}});if(r.data.ResponseCode!=="0")return res.status(400).json({success:false,message:r.data.ResponseDescription||"STK request failed",raw:r.data});payments.set(r.data.CheckoutRequestID,{status:"pending",createdAt:Date.now(),phone,amount});res.json({success:true,checkoutRequestId:r.data.CheckoutRequestID,merchantRequestId:r.data.MerchantRequestID})}catch(e){console.error(e.response?.data||e.message);res.status(500).json({success:false,message:e.response?.data?.errorMessage||e.response?.data?.ResponseDescription||"Could not reach M-Pesa"})}});
app.post("/api/mpesa/callback",(req,res)=>{const cb=req.body?.Body?.stkCallback;if(cb){const p=payments.get(cb.CheckoutRequestID);if(p){if(cb.ResultCode===0){const item=cb.CallbackMetadata?.Item||[];p.status="completed";p.receipt=item.find(x=>x.Name==="MpesaReceiptNumber")?.Value||"N/A"}else{p.status="failed";p.message=cb.ResultDesc||"Payment failed"}}}res.json({ResultCode:0,ResultDesc:"Accepted"})});
app.get("/api/mpesa/status/:id",(req,res)=>{const p=payments.get(req.params.id);if(!p)return res.json({status:"pending"});if(p.status==="completed")return res.json({status:"completed",receipt:p.receipt});if(p.status==="failed")return res.json({status:"failed",message:p.message});if(Date.now()-p.createdAt>300000){p.status="failed";p.message="Payment request timed out";return res.json({status:"failed",message:p.message})}res.json({status:"pending"})});
app.listen(PORT,"0.0.0.0",()=>console.log(`TIFFAS backend listening on ${PORT}`));
