const REPO="Tiffasbeautyandcosmetics/Tiffasbeauty-cosmetics-store",API="https://api.github.com",DB_NAME="tiffas_admin_offline_v1",DB_STORE="state",SYNC_TAG="tiffas-admin-sync";let token="",products=[],settings={},editing=-1,deletedIds=new Set(),offlineDirty=false,settingsDirty=false;
const $=id=>document.getElementById(id);
const headers=()=>({"Accept":"application/vnd.github+json","Authorization":"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28"});
function status(msg,error=false){if(!$("status"))return;$("status").textContent=msg;$("status").className="status "+(error?"error":"");}
function loginStatus(msg,error=false){if(!$("statusLogin"))return;$("statusLogin").textContent=msg;$("statusLogin").className="status "+(error?"error":"");}
function esc(s){return String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));}
function slug(s){return String(s||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"product";}
function uniqueId(name,index=-1){let base=slug(name),id=base,n=2;while(products.some((p,i)=>i!==index&&p.id===id))id=base+"-"+n++;return id;}
function decode(b64){const bin=atob(b64.replace(/\n/g,""));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes);}
function encode(text){const bytes=new TextEncoder().encode(text);let bin="";bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin);}
async function github(path,options={}){const r=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||`GitHub API HTTP ${r.status}`);return d;}
async function getFile(path){const d=await github("/repos/"+REPO+"/contents/"+path+"?ref=main");return{content:decode(d.content),sha:d.sha};}
async function putFile(path,content,sha,message){return github("/repos/"+REPO+"/contents/"+path,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,content:encode(content),sha,branch:"main"})});}
function dbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DB_STORE))r.result.createObjectStore(DB_STORE);};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error("Offline storage unavailable"));});}
async function dbGet(){const db=await dbOpen();return new Promise((resolve,reject)=>{const r=db.transaction(DB_STORE,"readonly").objectStore(DB_STORE).get("snapshot");r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);});}
async function dbPut(state){const db=await dbOpen();return new Promise((resolve,reject)=>{const r=db.transaction(DB_STORE,"readwrite").objectStore(DB_STORE).put(state,"snapshot");r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
async function dbClear(){const db=await dbOpen();return new Promise((resolve,reject)=>{const r=db.transaction(DB_STORE,"readwrite").objectStore(DB_STORE).delete("snapshot");r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
async function requestPersistentStorage(){try{if(navigator.storage?.persist)await navigator.storage.persist();}catch(_){}}
async function saveDeviceCopy(){const state={products,settings,deletedIds:[...deletedIds],offlineDirty:false,settingsDirty:false,rememberDevice:$("rememberDevice")?.checked!==false,token:($("rememberDevice")?.checked!==false?token:""),updatedAt:new Date().toISOString()};await dbPut(state);requestPersistentStorage();}
async function saveOfflineSnapshot(msg="Saved on this device."){offlineDirty=true;const state={products,settings,deletedIds:[...deletedIds],offlineDirty:true,settingsDirty,rememberDevice:$("rememberDevice")?.checked!==false,token:($("rememberDevice")?.checked!==false?token:""),updatedAt:new Date().toISOString()};await dbPut(state);requestPersistentStorage();try{if(navigator.serviceWorker?.ready)navigator.serviceWorker.ready.then(reg=>reg.sync?.register(SYNC_TAG)).catch(()=>{});}catch(_){};updateSyncBadge();status(msg);}
async function clearOfflineDirty(){offlineDirty=false;settingsDirty=false;const s=await dbGet();await dbPut({...s,products,settings,deletedIds:[...deletedIds],offlineDirty:false,settingsDirty:false,updatedAt:new Date().toISOString()});updateSyncBadge();}
function updateSyncBadge(){const toolbar=$(".toolbar");if(!toolbar)return;let b=$("syncBadge");if(!b){b=document.createElement("span");b.id="syncBadge";b.className="sync-badge";$("status")?.appendChild(b);}if(!navigator.onLine){b.textContent="Offline saved";b.className="sync-badge offline";}else if(offlineDirty||settingsDirty){b.textContent="Pending sync";b.className="sync-badge pending";}else{b.textContent="Online";b.className="sync-badge";}}
function showApp(){ $("loginPanel").classList.add("hidden"); $("app").classList.remove("hidden"); updateSyncBadge();}
function resolve(p){if(!p)return"";return/^(https?:|data:|blob:)/i.test(p)?p:new URL(p.replace(/^\//,""),location.href).href;}
function draw(){const q=($("search").value||"").toLowerCase();const list=products.map((p,i)=>({p,i})).filter(x=>(x.p.name||"").toLowerCase().includes(q)||(x.p.category||"").toLowerCase().includes(q));$("rows").innerHTML=list.map(({p,i})=>`<tr><td>${p.image?`<img class="thumb" src="${esc(resolve(p.image))}" alt="">`:"—"}</td><td><b>${esc(p.name)}</b><small>${esc(p.id)}</small></td><td>${esc(p.category||"")}</td><td>Ksh ${Number(p.price||0).toLocaleString("en-KE")}</td><td>${p.stockQty??0}</td><td>${p.inStock?"Yes":"No"}</td><td><div class="actions"><button data-edit="${i}" class="btn light">Edit</button><button data-del="${i}" class="btn danger">Delete</button></div></td></tr>`).join("");$("count").textContent=list.length+" shown / "+products.length+" products";}
function fillSettings(){$("bankName").value=settings.bankName||"";$("accountName").value=settings.accountName||"";$("accountNumber").value=settings.accountNumber||"";$("branch").value=settings.branch||"";$("swiftCode").value=settings.swiftCode||"";$("paymentInstructions").value=settings.paymentInstructions||"";$("waNumber").value=settings.whatsappNumber||"254725679016";$("cloudinaryCloudName").value=settings.cloudinaryCloudName||"";$("cloudinaryUploadPreset").value=settings.cloudinaryUploadPreset||"";}
function openProduct(i=-1){editing=i;const p=i>=0?products[i]:{id:"",name:"",category:"Beauty & Cosmetics",description:"",price:0,stockQty:0,inStock:true,image:null};$("productModal").classList.add("open");$("mName").value=p.name||"";$("mCategory").value=p.category||"Beauty & Cosmetics";$("mDescription").value=p.description||"";$("mPrice").value=p.price??0;$("mQty").value=p.stockQty??0;$("mStock").checked=p.inStock!==false;$("mImage").value="";$("preview").src=resolve(p.image||"");$("currentImage").textContent=p.image||"No image selected";}
function closeProduct(){$("productModal").classList.remove("open");}
function readImage(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});}
async function uploadGitHubBackup(blob,name){const ab=await blob.arrayBuffer(),bytes=new Uint8Array(ab);let binary="";const step=0x8000;for(let i=0;i<bytes.length;i+=step)binary+=String.fromCharCode(...bytes.subarray(i,i+step));const filename=slug(name)+"-"+Date.now()+".jpg";const body={message:"TIFFAS image backup: "+name,content:btoa(binary),branch:"main"};await github("/repos/"+REPO+"/contents/images/products/"+filename,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});return"images/products/"+filename;}
async function verifyImage(url){return new Promise(resolve=>{const img=new Image();let done=false;const finish=ok=>{if(done)return;done=true;clearTimeout(t);resolve(ok);};const t=setTimeout(()=>finish(false),7000);img.onload=()=>finish(true);img.onerror=()=>finish(false);img.src=url+(url.includes("?")?"&":"?")+"verify="+Date.now();});}
async function uploadImage(file,name){const raw=await readImage(file),img=new Image();img.src=raw;await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;});const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(res=>canvas.toBlob(res,"image/jpeg",.84));if(!blob||blob.size>1500000)throw Error("Image is too large after compression.");let cloudinaryUrl="";if(settings.cloudinaryCloudName&&settings.cloudinaryUploadPreset){try{const form=new FormData();form.append("file",blob,slug(name)+"-"+Date.now()+".jpg");form.append("upload_preset",settings.cloudinaryUploadPreset);const endpoint="https://api.cloudinary.com/v1_1/"+encodeURIComponent(settings.cloudinaryCloudName)+"/image/upload";const cr=await fetch(endpoint,{method:"POST",body:form});const d=await cr.json().catch(()=>({}));if(cr.ok&&d.secure_url)cloudinaryUrl=d.secure_url;}catch(_){}}if(cloudinaryUrl&&await verifyImage(cloudinaryUrl))return{url:cloudinaryUrl,cloudinaryUrl};const backup=await uploadGitHubBackup(blob,name);return{url:backup,cloudinaryUrl:cloudinaryUrl||""};}
async function loadOnline(){status("Loading GitHub catalogue…");const a=await getFile("catalog/products.json"),b=await getFile("store-settings.json");products=JSON.parse(a.content);settings=JSON.parse(b.content);deletedIds=new Set();offlineDirty=false;settingsDirty=false;await saveDeviceCopy();draw();fillSettings();status(products.length+" products loaded from GitHub.");updateSyncBadge();}
async function loadOffline(){const s=await dbGet();if(!s?.products?.length)throw Error("No offline catalogue has been saved on this device yet.");products=s.products;settings=s.settings||{};deletedIds=new Set(s.deletedIds||[]);offlineDirty=!!s.offlineDirty;settingsDirty=!!s.settingsDirty;showApp();draw();fillSettings();status("Offline mode. Changes are saved on this device and queued for sync.");updateSyncBadge();}
async function publishCatalogue(){if(!navigator.onLine){await saveOfflineSnapshot("Internet unavailable. Catalogue saved offline and queued for sync.");return;}status("Syncing latest catalogue with GitHub…");const fresh=await getFile("catalog/products.json");const remote=JSON.parse(fresh.content);const localById=new Map(products.map(p=>[String(p.id),p]));const merged=[];for(const p of remote){const id=String(p.id);if(deletedIds.has(id))continue;merged.push(localById.has(id)?localById.get(id):p);localById.delete(id);}for(const p of localById.values())merged.push(p);products=merged;await putFile("catalog/products.json",JSON.stringify(products,null,2),fresh.sha,"Update TIFFAS product catalogue");deletedIds=new Set();offlineDirty=false;const s=await dbGet();await dbPut({...s,products,settings,deletedIds:[],offlineDirty:false,settingsDirty:false,updatedAt:new Date().toISOString()});draw();status("Published and synchronized "+products.length+" products. New products from other sessions were preserved.");updateSyncBadge();}
async function syncOffline(){if(!navigator.onLine||!offlineDirty&&!settingsDirty)return;if(!token){status("Offline changes are saved. Connect GitHub to upload them.",true);return;}try{status("Internet restored. Uploading offline changes…");const fresh=await getFile("catalog/products.json");const remote=JSON.parse(fresh.content);const localById=new Map(products.map(p=>[String(p.id),p]));const merged=[];for(const p of remote){const id=String(p.id);if(deletedIds.has(id))continue;merged.push(localById.has(id)?localById.get(id):p);localById.delete(id);}for(const p of localById.values())merged.push(p);products=merged;for(const p of products){if(typeof p.image==="string"&&p.image.startsWith("data:")){const res=await uploadImage(await (await fetch(p.image)).blob(),p.name);p.image=res.url;if(res.cloudinaryUrl)p.cloudinaryImage=res.cloudinaryUrl;if(res.url!==res.cloudinaryUrl)p.fallbackImage=res.url;}}await putFile("catalog/products.json",JSON.stringify(products,null,2),fresh.sha,"Sync offline TIFFAS catalogue changes");if(settingsDirty){const sf=await getFile("store-settings.json");await putFile("store-settings.json",JSON.stringify(settings,null,2),sf.sha,"Sync offline TIFFAS store settings");}deletedIds=new Set();offlineDirty=false;settingsDirty=false;await dbPut({products,settings,deletedIds:[],offlineDirty:false,settingsDirty:false,rememberDevice:$("rememberDevice")?.checked!==false,token:($("rememberDevice")?.checked!==false?token:""),updatedAt:new Date().toISOString()});draw();fillSettings();status("Offline changes uploaded successfully.");updateSyncBadge();}catch(e){status("Sync pending: "+e.message,true);await saveOfflineSnapshot("Sync failed; changes remain safely saved offline.");}}
async function maybeRegisterSync(){try{const reg=await navigator.serviceWorker?.ready;if(reg?.sync)await reg.sync.register(SYNC_TAG);}catch(_){}}
$("login").onclick=async()=>{const v=$("token").value.trim();if(v)token=v;else if(!token)return loginStatus("Paste your GitHub fine-grained token.",true);loginStatus("Checking GitHub access…");try{const d=await github("/repos/"+REPO);if(!d.permissions?.push)throw Error("This token does not have write access to the repository.");if($("rememberDevice")?.checked!==false){await dbPut({...(await dbGet()||{}),token,rememberDevice:true});}sessionStorage.setItem("tiffas_admin_token",token);showApp();if(navigator.onLine)await loadOnline();else await loadOffline();}catch(e){if(!navigator.onLine){try{await loadOffline();loginStatus("GitHub is offline. Working from the saved device catalogue.");}catch(_){loginStatus("No saved offline catalogue is available yet.",true);}}else loginStatus(e.message,true);}};
$("offlineMode").onclick=async()=>{try{await loadOffline();}catch(e){loginStatus(e.message,true);}};
$("logout").onclick=async()=>{sessionStorage.removeItem("tiffas_admin_token");token="";const s=await dbGet().catch(()=>null);if(s&&!$("rememberDevice")?.checked)await dbPut({...s,token:"",rememberDevice:false});location.reload();};
$("search").oninput=draw;$("add").onclick=()=>openProduct(-1);$("cancelProduct").onclick=closeProduct;$("cancelProduct2").onclick=closeProduct;
$("rows").onclick=e=>{const ed=e.target.closest("[data-edit]"),del=e.target.closest("[data-del]");if(ed)openProduct(Number(ed.dataset.edit));if(del){const i=Number(del.dataset.del);if(confirm("Delete this product from the catalogue?")){const removed=products[i];if(removed?.id)deletedIds.add(String(removed.id));products.splice(i,1);draw();if(navigator.onLine)publishCatalogue().catch(e=>{offlineDirty=true;saveOfflineSnapshot("Delete saved offline after sync error.");});else saveOfflineSnapshot("Delete saved offline.");}}};
$("mImage").onchange=async()=>{const f=$("mImage").files[0];if(!f)return;try{$("preview").src=await readImage(f);$("currentImage").textContent=f.name;}catch(_){}};
$("saveProduct").onclick=async()=>{const name=$("mName").value.trim();if(!name)return alert("Product name is required.");const i=editing,p=i>=0?products[i]:{id:"",image:null};p.name=name;p.id=uniqueId(name,i);p.category=$("mCategory").value.trim()||"Beauty & Cosmetics";p.description=$("mDescription").value.trim();p.price=Number($("mPrice").value||0);p.stockQty=Number($("mQty").value||0);p.inStock=$("mStock").checked;const f=$("mImage").files[0];try{$("saveProduct").disabled=true;$("saveProduct").textContent=f&&!navigator.onLine?"Saving offline…":f?"Uploading image…":"Saving…";if(f){if(navigator.onLine){const uploaded=await uploadImage(f,name);p.image=uploaded.url;if(uploaded.cloudinaryUrl)p.cloudinaryImage=uploaded.cloudinaryUrl;if(uploaded.url!==uploaded.cloudinaryUrl)p.fallbackImage=uploaded.url;}else{p.image=await readImage(f);}}if(i<0)products.unshift(p);if(navigator.onLine){try{await publishCatalogue();}catch(e){offlineDirty=true;await saveOfflineSnapshot("Online save failed. Product kept offline for automatic sync.");}}else{await saveOfflineSnapshot("Product saved offline on this device.");}draw();closeProduct();}catch(e){alert(e.message);status(e.message,true);}finally{$("saveProduct").disabled=false;$("saveProduct").textContent="Save product";}};
$("saveCatalogue").onclick=async()=>{try{await publishCatalogue();}catch(e){await saveOfflineSnapshot("Catalogue saved offline after sync failure.");}};
$("saveOffline").onclick=async()=>{try{await saveOfflineSnapshot("Catalogue saved on this device. It will sync when internet returns.");await maybeRegisterSync();}catch(e){status("Offline save failed: "+e.message,true);}};
$("syncNow").onclick=async()=>{if(!navigator.onLine)return saveOfflineSnapshot("Still offline. Changes remain safely stored on this device.");try{await syncOffline();if(!offlineDirty&&!settingsDirty)await loadOnline();}catch(e){status(e.message,true);}};
$("reload").onclick=()=>{if(navigator.onLine)loadOnline().catch(e=>status(e.message,true));else loadOffline().catch(e=>status(e.message,true));};
$("openSettings").onclick=()=>{$("settingsModal").classList.add("open");fillSettings();};$("closeSettings").onclick=()=>$("settingsModal").classList.remove("open");$("cancelSettings").onclick=()=>fillSettings();
$("saveSettings").onclick=async()=>{settings={...settings,bankName:$("bankName").value.trim(),accountName:$("accountName").value.trim(),accountNumber:$("accountNumber").value.trim(),branch:$("branch").value.trim(),swiftCode:$("swiftCode").value.trim(),paymentInstructions:$("paymentInstructions").value.trim(),whatsappNumber:$("waNumber").value.trim(),cloudinaryCloudName:$("cloudinaryCloudName").value.trim(),cloudinaryUploadPreset:$("cloudinaryUploadPreset").value.trim()};try{if(navigator.onLine&&token){status("Saving store settings…");const fresh=await getFile("store-settings.json");await putFile("store-settings.json",JSON.stringify(settings,null,2),fresh.sha,"Update store and Cloudinary settings");await saveOfflineSnapshot("Store settings published and saved offline.");$("settingsModal").classList.remove("open");}else{settingsDirty=true;await saveOfflineSnapshot("Store settings saved offline.");$("settingsModal").classList.remove("open");}}catch(e){settingsDirty=true;await saveOfflineSnapshot("Settings saved offline after sync error.");$("settingsModal").classList.remove("open");}};
window.addEventListener("online",async()=>{updateSyncBadge();loginStatus("Internet restored. Syncing…");if(!token){const s=await dbGet().catch(()=>null);if(s?.token)token=s.token;}if(token)await syncOffline().catch(()=>{});});
window.addEventListener("offline",()=>{updateSyncBadge();status("Offline mode. Changes will stay on this device.");});
if(navigator.serviceWorker)navigator.serviceWorker.addEventListener("message",e=>{if(e.data?.type==="sync-complete"){offlineDirty=false;settingsDirty=false;loadOnline().catch(()=>{});}});
(async()=>{await requestPersistentStorage();const saved=await dbGet().catch(()=>null);if(saved?.rememberDevice&&saved.token){token=saved.token;$("rememberDevice").checked=true;}const session=sessionStorage.getItem("tiffas_admin_token");if(session)token=session;if(token&&navigator.onLine){$("token").value=token;setTimeout(()=>$("login").click(),50);}else if(!navigator.onLine&&saved?.products?.length){try{await loadOffline();}catch(_){} }})();