const REPO="Tiffasbeautyandcosmetics/Tiffasbeauty-cosmetics-store",API="https://api.github.com";let token="",products=[],settings={},editing=-1;
const $=id=>document.getElementById(id);
const headers=()=>({"Accept":"application/vnd.github+json","Authorization":"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28"});
function status(msg,error=false){$("status").textContent=msg;$("status").className="status "+(error?"error":"");}
function loginStatus(msg,error=false){$("statusLogin").textContent=msg;$("statusLogin").className="status "+(error?"error":"");}
function esc(s){return String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));}
function slug(s){return String(s||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"product";}
function uniqueId(name,index=-1){let base=slug(name),id=base,n=2;while(products.some((p,i)=>i!==index&&p.id===id))id=base+"-"+n++;return id;}
function decode(b64){return decodeURIComponent(escape(atob(b64.replace(/\n/g,""))));}
function encode(text){return btoa(unescape(encodeURIComponent(text)));}
async function github(path,options={}){const r=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||`GitHub API HTTP ${r.status}`);return d;}
async function getFile(path){const d=await github("/repos/"+REPO+"/contents/"+path+"?ref=main");return{content:decode(d.content),sha:d.sha};}
async function putFile(path,content,sha,message){return github("/repos/"+REPO+"/contents/"+path,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,content:encode(content),sha,branch:"main"})});}
async function load(){status("Loading GitHub catalogue…");const a=await getFile("catalog/products.json"),b=await getFile("store-settings.json");products=JSON.parse(a.content);settings=JSON.parse(b.content);draw();fillSettings();status(products.length+" products loaded from GitHub.");}
function resolve(p){if(!p)return"";return/^(https?:|data:|blob:)/i.test(p)?p:new URL(p.replace(/^\//,""),location.href).href;}
function draw(){const q=($("search").value||"").toLowerCase();const list=products.map((p,i)=>({p,i})).filter(x=>(x.p.name||"").toLowerCase().includes(q)||(x.p.category||"").toLowerCase().includes(q));$("rows").innerHTML=list.map(({p,i})=>`<tr><td>${p.image?`<img class="thumb" src="${esc(resolve(p.image))}" alt="">`:"—"}</td><td><b>${esc(p.name)}</b><small>${esc(p.id)}</small></td><td>${esc(p.category||"")}</td><td>Ksh ${Number(p.price||0).toLocaleString("en-KE")}</td><td>${p.stockQty??0}</td><td>${p.inStock?"Yes":"No"}</td><td><div class="actions"><button data-edit="${i}" class="btn light">Edit</button><button data-del="${i}" class="btn danger">Delete</button></div></td></tr>`).join("");$("count").textContent=list.length+" shown / "+products.length+" products";}
function fillSettings(){$("bankName").value=settings.bankName||"";$("accountName").value=settings.accountName||"";$("accountNumber").value=settings.accountNumber||"";$("branch").value=settings.branch||"";$("swiftCode").value=settings.swiftCode||"";$("paymentInstructions").value=settings.paymentInstructions||"";$("waNumber").value=settings.whatsappNumber||"254725679016";$("cloudinaryCloudName").value=settings.cloudinaryCloudName||"";$("cloudinaryUploadPreset").value=settings.cloudinaryUploadPreset||"";}
function openProduct(i=-1){editing=i;const p=i>=0?products[i]:{id:"",name:"",category:"Beauty & Cosmetics",description:"",price:0,stockQty:0,inStock:true,image:null};$("productModal").classList.add("open");$("mName").value=p.name||"";$("mCategory").value=p.category||"Beauty & Cosmetics";$("mDescription").value=p.description||"";$("mPrice").value=p.price??0;$("mQty").value=p.stockQty??0;$("mStock").checked=p.inStock!==false;$("mImage").value="";$("preview").src=resolve(p.image||"");$("currentImage").textContent=p.image||"No image selected";}
function closeProduct(){$("productModal").classList.remove("open");}
function readImage(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});}
async function uploadImage(file,name){if(!settings.cloudinaryCloudName||!settings.cloudinaryUploadPreset)throw Error("Configure Cloudinary cloud name and unsigned upload preset in Store settings before uploading an image.");const raw=await readImage(file),img=new Image();img.src=raw;await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;});const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(res=>canvas.toBlob(res,"image/jpeg",.84));if(!blob||blob.size>1500000)throw Error("Image is too large after compression.");const form=new FormData();form.append("file",blob,slug(name)+"-"+Date.now()+".jpg");form.append("upload_preset",settings.cloudinaryUploadPreset);const endpoint="https://api.cloudinary.com/v1_1/"+encodeURIComponent(settings.cloudinaryCloudName)+"/image/upload";const r=await fetch(endpoint,{method:"POST",body:form});const d=await r.json().catch(()=>({}));if(!r.ok||!d.secure_url)throw Error(d.error?.message||"Cloudinary image upload failed.");return d.secure_url;}
$("login").onclick=async()=>{const v=$("token").value.trim();if(!v)return loginStatus("Paste your GitHub fine-grained token.",true);token=v;loginStatus("Checking GitHub access…");try{const d=await github("/repos/"+REPO);if(!d.permissions?.push)throw Error("This token does not have write access to the repository.");sessionStorage.setItem("tiffas_admin_token",token);$("loginPanel").classList.add("hidden");$("app").classList.remove("hidden");await load();}catch(e){loginStatus(e.message,true);}};
token=sessionStorage.getItem("tiffas_admin_token")||"";
$("logout").onclick=()=>{sessionStorage.removeItem("tiffas_admin_token");location.reload();};
$("search").oninput=draw;$("add").onclick=()=>openProduct(-1);$("cancelProduct").onclick=closeProduct;$("cancelProduct2").onclick=closeProduct;
$("rows").onclick=e=>{const ed=e.target.closest("[data-edit]"),del=e.target.closest("[data-del]");if(ed)openProduct(Number(ed.dataset.edit));if(del){const i=Number(del.dataset.del);if(confirm("Delete this product from the catalogue?")){products.splice(i,1);draw();publishCatalogue().catch(e=>status(e.message,true));}}};
$("mImage").onchange=async()=>{const f=$("mImage").files[0];if(!f)return;try{$("preview").src=await readImage(f);$("currentImage").textContent=f.name;}catch(_){}};
async function publishCatalogue(){status("Publishing catalogue to GitHub…");const fresh=await getFile("catalog/products.json");await putFile("catalog/products.json",JSON.stringify(products,null,2),fresh.sha,"Update TIFFAS product catalogue");status("Published "+products.length+" products. The customer store will pick up the update automatically.");}
$("saveProduct").onclick=async()=>{const name=$("mName").value.trim();if(!name)return alert("Product name is required.");const i=editing,p=i>=0?products[i]:{id:"",image:null};p.name=name;p.id=uniqueId(name,i);p.category=$("mCategory").value.trim()||"Beauty & Cosmetics";p.description=$("mDescription").value.trim();p.price=Number($("mPrice").value||0);p.stockQty=Number($("mQty").value||0);p.inStock=$("mStock").checked;const f=$("mImage").files[0];try{$("saveProduct").disabled=true;$("saveProduct").textContent=f?"Uploading image…":"Publishing product…";if(f)p.image=await uploadImage(f,name);if(i<0)products.unshift(p);await publishCatalogue();draw();closeProduct();}catch(e){alert(e.message);status(e.message,true);}finally{$("saveProduct").disabled=false;$("saveProduct").textContent="Save product";}};
$("saveCatalogue").onclick=async()=>{try{await publishCatalogue();}catch(e){status(e.message,true);}};
$("reload").onclick=()=>load().catch(e=>status(e.message,true));
$("openSettings").onclick=()=>{$("settingsModal").classList.add("open");fillSettings();};$("closeSettings").onclick=()=>$("settingsModal").classList.remove("open");$("cancelSettings").onclick=()=>fillSettings();
$("saveSettings").onclick=async()=>{settings={...settings,bankName:$("bankName").value.trim(),accountName:$("accountName").value.trim(),accountNumber:$("accountNumber").value.trim(),branch:$("branch").value.trim(),swiftCode:$("swiftCode").value.trim(),paymentInstructions:$("paymentInstructions").value.trim(),whatsappNumber:$("waNumber").value.trim(),cloudinaryCloudName:$("cloudinaryCloudName").value.trim(),cloudinaryUploadPreset:$("cloudinaryUploadPreset").value.trim()};try{status("Saving store settings…");const fresh=await getFile("store-settings.json");await putFile("store-settings.json",JSON.stringify(settings,null,2),fresh.sha,"Update store and Cloudinary settings");status("Store settings published to GitHub.");$("settingsModal").classList.remove("open");}catch(e){status(e.message,true);}};
if(token){$("token").value=token;setTimeout(()=>$("login").click(),50);}
