const REPO="Tiffasbeautyandcosmetics/Tiffasbeauty-cosmetics-store",API="https://api.github.com",DB_NAME="tiffas_admin_offline_v3",DB_STORE="state";
let token="",products=[],settings={},editing=-1,deletedIds=new Set(),offlineDirty=false,settingsDirty=false,viewMode=localStorage.getItem("tiffas_admin_view")||"list";
const $=id=>document.getElementById(id),money=n=>"Ksh "+Number(n||0).toLocaleString("en-KE",{maximumFractionDigits:2});
function esc(s){return String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
function slug(s){return String(s||"product").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"product"}
function uniqueId(name,index=-1){let b=slug(name),id=b,n=2;while(products.some((p,i)=>i!==index&&p.id===id))id=b+"-"+n++;return id}
function status(msg,error=false){const e=$("status");if(e){e.textContent=msg;e.className="status "+(error?"error":"")}}
function loginStatus(msg,error=false){const e=$("statusLogin");if(e){e.textContent=msg;e.className="status "+(error?"error":"")}}
function encode(t){const b=new TextEncoder().encode(t);let s="";b.forEach(x=>s+=String.fromCharCode(x));return btoa(s)}
function decode(b){const s=atob(String(b||"").replace(/\n/g,""));return new TextDecoder().decode(Uint8Array.from(s,c=>c.charCodeAt(0)))}
function headers(){return{Accept:"application/vnd.github+json",Authorization:"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28"}}
async function github(path,opt={}){let r;try{r=await fetch(API+path,{...opt,headers:{...headers(),...(opt.headers||{})}})}catch(_){throw Error("Cannot reach GitHub. Check your internet connection.")}const d=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401||r.status===403)throw Error("GitHub rejected this token. Use a fine-grained token with Contents: Read and write.");throw Error(d.message||("GitHub API HTTP "+r.status))}return d}
async function getFile(path){const d=await github("/repos/"+REPO+"/contents/"+path+"?ref=main");return{content:decode(d.content),sha:d.sha}}
async function putFile(path,content,sha,message){return github("/repos/"+REPO+"/contents/"+path,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,content:encode(content),sha,branch:"main"})})}
function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DB_STORE))r.result.createObjectStore(DB_STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error||Error("Offline storage unavailable"))})}
async function dbGet(){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction(DB_STORE,"readonly").objectStore(DB_STORE).get("snapshot");r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function dbPut(v){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction(DB_STORE,"readwrite").objectStore(DB_STORE).put(v,"snapshot");r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function saveState(dirty){await dbPut({products,settings,deletedIds:[...deletedIds],offlineDirty:!!dirty,settingsDirty,rememberDevice:$("rememberDevice")?.checked!==false,token:$("rememberDevice")?.checked!==false?token:"",updatedAt:new Date().toISOString()})}
function resolveAsset(p){if(!p)return"";return/^(https?:|data:|blob:)/i.test(p)?p:new URL(p.replace(/^\//,""),location.href).href}
function updateConnection(){const e=$("connection");const pending=offlineDirty||settingsDirty;if(e){e.textContent=!navigator.onLine?"Offline":pending?"Pending sync":"Online";e.className="connection "+(!navigator.onLine?"":pending?"pending":"online")}const b=$("syncBadge");if(b)b.textContent=!navigator.onLine?"Offline":pending?"Pending sync":"Online"}
function setViewMode(m,persist=true){viewMode=m==="grid"?"grid":"list";if(persist)localStorage.setItem("tiffas_admin_view",viewMode);$("tablePanel")?.classList.toggle("hidden-view",viewMode!=="list");$("gridPanel")?.classList.toggle("hidden-view",viewMode!=="grid");$("listView")?.classList.toggle("active",viewMode==="list");$("gridView")?.classList.toggle("active",viewMode==="grid")}
function draw(){const q=($("search")?.value||"").toLowerCase().trim();const list=products.map((p,i)=>({p,i})).filter(x=>(String(x.p.name||"")+" "+String(x.p.id||"")+" "+String(x.p.category||"")).toLowerCase().includes(q));if($("rows"))$("rows").innerHTML=list.map(x=>"<tr><td>"+(x.p.image?'<img class="thumb" src="'+esc(resolveAsset(x.p.image))+'" alt="">':"—")+"</td><td><b>"+esc(x.p.name)+"</b><small>"+esc(x.p.id)+"</small></td><td>"+esc(x.p.category||"")+"</td><td>"+money(x.p.price)+"</td><td>"+(x.p.stockQty??0)+"</td><td><span class=\"stock-pill "+(x.p.inStock?"in":"out")+"\">"+(x.p.inStock?"In stock":"Out of stock")+"</span></td><td><div class=\"actions\"><button class=\"btn light\" data-edit=\""+x.i+"\">Edit</button><button class=\"btn danger\" data-del=\""+x.i+"\">Delete</button></div></td></tr>").join("");if($("grid"))$("grid").innerHTML=list.map(x=>"<article class=\"product-card\"><div class=\"product-card-image\">"+(x.p.image?'<img src="'+esc(resolveAsset(x.p.image))+'" alt="'+esc(x.p.name)+'" loading="lazy">':"<div class=\"no-image\">No image</div>")+"</div><div class=\"product-card-body\"><small>"+esc(x.p.category||"Uncategorized")+"</small><h3>"+esc(x.p.name)+"</h3><div class=\"product-meta\"><strong>"+money(x.p.price)+"</strong><span>Qty: "+(x.p.stockQty??0)+"</span></div><div class=\"actions\"><button class=\"btn light\" data-edit=\""+x.i+"\">Edit</button><button class=\"btn danger\" data-del=\""+x.i+"\">Delete</button></div></div></article>").join("");if($("count"))$("count").textContent=list.length+" shown / "+products.length+" products";setViewMode(viewMode,false)}
function fillSettings(){if(!$("bankName"))return;$("bankName").value=settings.bankName||"";$("accountName").value=settings.accountName||"";$("accountNumber").value=settings.accountNumber||"";$("branch").value=settings.branch||"";$("swiftCode").value=settings.swiftCode||"";$("waNumber").value=settings.whatsappNumber||"254725679016";$("paymentInstructions").value=settings.paymentInstructions||"";$("cloudinaryCloudName").value=settings.cloudinaryCloudName||"";$("cloudinaryUploadPreset").value=settings.cloudinaryUploadPreset||""}
function showApp(){ $("loginPanel")?.classList.add("hidden");$("app")?.classList.remove("hidden");draw();fillSettings();updateConnection()}
function closeProduct(){$("productModal")?.classList.remove("open")}
function openProduct(i=-1){editing=i;const p=i>=0?products[i]:{name:"",category:"Beauty & Cosmetics",description:"",price:0,stockQty:20,inStock:true,image:null};$("productModal")?.classList.add("open");$("mName").value=p.name||"";$("mCategory").value=p.category||"Beauty & Cosmetics";$("mDescription").value=p.description||"";$("mPrice").value=p.price??0;$("mQty").value=p.stockQty??20;$("mStock").checked=p.inStock!==false;$("mImage").value="";$("preview").src=resolveAsset(p.image||"");$("currentImage").textContent=p.image||"No image selected"}
function readImage(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(f)})}
async function uploadImage(file,name){const raw=await readImage(file),img=new Image();img.src=raw;await new Promise((res,rej)=>{img.onload=res;img.onerror=rej});const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(res=>canvas.toBlob(res,"image/jpeg",.84));if(!blob)throw Error("Could not process image.");if(settings.cloudinaryCloudName&&settings.cloudinaryUploadPreset){try{const f=new FormData();f.append("file",blob,slug(name)+".jpg");f.append("upload_preset",settings.cloudinaryUploadPreset);const cr=await fetch("https://api.cloudinary.com/v1_1/"+encodeURIComponent(settings.cloudinaryCloudName)+"/image/upload",{method:"POST",body:f});const d=await cr.json().catch(()=>({}));if(cr.ok&&d.secure_url)return{url:d.secure_url}}catch(_){}}const ab=await blob.arrayBuffer(),bytes=new Uint8Array(ab);let bin="";for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));const fileName=slug(name)+"-"+Date.now()+".jpg";await github("/repos/"+REPO+"/contents/images/products/"+fileName,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:"TIFFAS product image: "+name,content:btoa(bin),branch:"main"})});return{url:"images/products/"+fileName}}
async function loadOnline(){status("Loading GitHub catalogue...");const [a,b]=await Promise.all([getFile("catalog/products.json"),getFile("store-settings.json")]);products=JSON.parse(a.content);settings=JSON.parse(b.content);deletedIds=new Set();offlineDirty=false;settingsDirty=false;await saveState(false);draw();fillSettings();status(products.length+" products loaded from GitHub.");updateConnection()}
async function loadOffline(){const s=await dbGet();if(!s?.products?.length)throw Error("No saved offline catalogue is available on this device yet.");products=s.products;settings=s.settings||{};deletedIds=new Set(s.deletedIds||[]);offlineDirty=!!s.offlineDirty;settingsDirty=!!s.settingsDirty;showApp();status("Offline copy loaded. Changes stay on this device until synced.")}
async function saveOffline(msg){offlineDirty=true;await saveState(true);status(msg||"Saved on this device. Changes are waiting to sync.");updateConnection()}
async function publishCatalogue(){if(!navigator.onLine){await saveOffline("Internet unavailable. Catalogue saved offline.");return}status("Syncing latest catalogue...");const f=await getFile("catalog/products.json"),remote=JSON.parse(f.content),localById=new Map(products.map(p=>[String(p.id),p])),merged=[];for(const p of remote){const id=String(p.id);if(deletedIds.has(id))continue;merged.push(localById.has(id)?localById.get(id):p);localById.delete(id)}for(const p of localById.values())merged.push(p);products=merged;await putFile("catalog/products.json",JSON.stringify(products,null,2),f.sha,"Update TIFFAS product catalogue");deletedIds=new Set();offlineDirty=false;await saveState(false);draw();status("Catalogue synchronized: "+products.length+" products.");updateConnection()}
async function saveSettingsOnline(){settings={...settings,bankName:$("bankName").value.trim(),accountName:$("accountName").value.trim(),accountNumber:$("accountNumber").value.trim(),branch:$("branch").value.trim(),swiftCode:$("swiftCode").value.trim(),whatsappNumber:$("waNumber").value.trim(),paymentInstructions:$("paymentInstructions").value.trim(),cloudinaryCloudName:$("cloudinaryCloudName").value.trim(),cloudinaryUploadPreset:$("cloudinaryUploadPreset").value.trim()};if(!navigator.onLine||!token){settingsDirty=true;return saveOffline("Settings saved offline.")}status("Saving store settings...");const f=await getFile("store-settings.json");await putFile("store-settings.json",JSON.stringify(settings,null,2),f.sha,"Update TIFFAS store settings");settingsDirty=false;await saveState(false);fillSettings();status("Store settings saved online.");updateConnection()}
$("login")?.addEventListener("click",async()=>{const v=$("token")?.value.trim();if(v)token=v;if(!token)return loginStatus("Paste your GitHub fine-grained token.",true);loginStatus("Checking GitHub access...");try{const r=await github("/repos/"+REPO);if(!r.permissions?.push)throw Error("This token does not have write access to the repository.");sessionStorage.setItem("tiffas_admin_token",token);if($("rememberDevice")?.checked)await dbPut({...((await dbGet().catch(()=>null))||{}),token,rememberDevice:true});showApp();await loadOnline()}catch(e){loginStatus(e.message,true)}});
$("offlineMode")?.addEventListener("click",async()=>{try{await loadOffline()}catch(e){loginStatus(e.message,true)}});
$("logout")?.addEventListener("click",()=>{sessionStorage.removeItem("tiffas_admin_token");token="";location.reload()});
$("add")?.addEventListener("click",()=>openProduct());$("cancelProduct")?.addEventListener("click",closeProduct);$("cancelProduct2")?.addEventListener("click",closeProduct);
$("mImage")?.addEventListener("change",async e=>{const f=e.target.files?.[0];if(f){$("preview").src=await readImage(f);$("currentImage").textContent=f.name}});
$("saveProduct")?.addEventListener("click",async()=>{try{const p=editing>=0?products[editing]:{};p.id=p.id||uniqueId($("mName").value,editing);p.name=$("mName").value.trim();p.category=$("mCategory").value.trim()||"Beauty & Cosmetics";p.description=$("mDescription").value.trim();p.price=Number($("mPrice").value||0);p.stockQty=Math.max(0,Number($("mQty").value||0));p.inStock=$("mStock").checked;const f=$("mImage").files?.[0];if(f){if(navigator.onLine&&token){const u=await uploadImage(f,p.name);p.image=u.url}else p.image=await readImage(f)}if(editing<0)products.unshift(p);closeProduct();draw();if(navigator.onLine&&token)await publishCatalogue();else await saveOffline("Product saved offline.")}catch(e){alert(e.message)}});
function handleCatalogueClick(e){const ed=e.target.closest("[data-edit]"),del=e.target.closest("[data-del]");if(ed)openProduct(Number(ed.dataset.edit));if(del){const i=Number(del.dataset.del);if(products[i]&&confirm("Delete "+products[i].name+"?")){deletedIds.add(String(products[i].id));products.splice(i,1);draw();saveOffline("Product deletion saved locally.")}}}
$("rows")?.addEventListener("click",handleCatalogueClick);$("grid")?.addEventListener("click",handleCatalogueClick);$("search")?.addEventListener("input",draw);$("listView")?.addEventListener("click",()=>setViewMode("list"));$("gridView")?.addEventListener("click",()=>setViewMode("grid"));
$("saveCatalogue")?.addEventListener("click",()=>publishCatalogue().catch(e=>status(e.message,true)));$("saveOffline")?.addEventListener("click",()=>saveOffline("Catalogue saved on this device."));$("syncNow")?.addEventListener("click",()=>publishCatalogue().catch(e=>status(e.message,true)));$("reload")?.addEventListener("click",()=>navigator.onLine?loadOnline().catch(e=>status(e.message,true)):loadOffline().catch(e=>status(e.message,true)));
$("openSettings")?.addEventListener("click",()=>{$("settingsModal")?.classList.add("open");fillSettings()});$("closeSettings")?.addEventListener("click",()=>$("settingsModal")?.classList.remove("open"));$("cancelSettings")?.addEventListener("click",()=>{$("settingsModal")?.classList.remove("open");fillSettings()});$("saveSettings")?.addEventListener("click",()=>saveSettingsOnline().catch(e=>{settingsDirty=true;saveOffline("Settings saved offline after sync error.")}));
window.addEventListener("online",()=>{updateConnection();if(token&&(offlineDirty||settingsDirty))publishCatalogue().catch(()=>{})});window.addEventListener("offline",updateConnection);
window.TIFFAS_ADMIN_CONTEXT={getFile,putFile,hasToken:()=>!!token,isOnline:()=>navigator.onLine,setStatus:(m,e=false)=>status(m,e),getToken:()=>token};
(async()=>{const saved=await dbGet().catch(()=>null),sess=sessionStorage.getItem("tiffas_admin_token");if(sess)token=sess;else if(saved?.rememberDevice&&saved.token)token=saved.token;if(token&&navigator.onLine){if($("token"))$("token").value=token;setTimeout(()=>$("login")?.click(),80)}else if(saved?.products?.length){products=saved.products;settings=saved.settings||{};offlineDirty=!!saved.offlineDirty;settingsDirty=!!saved.settingsDirty;showApp();status("Offline copy loaded. Connect GitHub to publish changes.")}})();