(()=>{
const KEY="tiffas_admin_orders_v1";let orders=[];
function q(id){return document.getElementById(id)}
function money(n){return "Ksh "+Number(n||0).toLocaleString("en-KE",{maximumFractionDigits:2})}
function esc(s){return String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",\"\": "&quot;"}[m]))}
function load(){try{orders=JSON.parse(localStorage.getItem(KEY)||"[]");if(!Array.isArray(orders))orders=[]}catch(e){orders=[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(orders));render();}
function render(){
 const host=q("app");if(!host||q("ordersPanel"))return;
 const p=document.createElement("section");p.id="ordersPanel";p.className="card order-panel";
 p.innerHTML="<div class=\"section-head\"><div><h2>Customer orders & receipts</h2><p>Orders are stored on this admin device. Customers can send order data through WhatsApp or export it for import here.</p></div><div class=\"actions\"><button id=\"orderAdd\" class=\"btn primary\">+ Record order</button><button id=\"orderImport\" class=\"btn light\">Import order JSON</button><button id=\"orderExport\" class=\"btn light\">Export orders</button></div></div><div class=\"filters\"><input id=\"orderSearch\" class=\"search\" placeholder=\"Search order, customer or phone…\"><select id=\"orderFilter\"><option value=\"\">All statuses</option><option>Pending</option><option>Confirmed</option><option>Packed</option><option>Out for delivery</option><option>Delivered</option><option>Cancelled</option></select></div><div class=\"table-wrap\"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th></th></tr></thead><tbody id=\"orderRows\"></tbody></table></div><div id=\"orderEmpty\" class=\"empty\">No customer orders recorded yet.</div>";
 host.querySelector(".toolbar")?.after(p);
 q("orderAdd").onclick=()=>edit();q("orderImport").onclick=importOrder;q("orderExport").onclick=()=>download("tiffas-orders.json",JSON.stringify(orders,null,2));q("orderSearch").oninput=renderRows;q("orderFilter").onchange=renderRows;renderRows();
}
function renderRows(){const body=q("orderRows"),empty=q("orderEmpty");if(!body)return;const s=(q("orderSearch")?.value||"").toLowerCase(),f=q("orderFilter")?.value||"";const list=orders.filter(o=>(!s||JSON.stringify(o).toLowerCase().includes(s))&&(!f||o.status===f));body.innerHTML=list.map(o=>"<tr><td><b>"+esc(o.orderNumber)+"</b><small>"+new Date(o.createdAt||Date.now()).toLocaleString("en-KE")+"</small></td><td>"+esc(o.customer?.name||"Customer")+"<small>"+esc(o.customer?.phone||"")+"</small></td><td>"+money(o.total)+"</td><td>"+esc(o.paymentStatus||"Unpaid")+"</td><td>"+esc(o.status||"Pending")+"</td><td><div class=\"actions\"><button class=\"btn light\" data-order-view=\""+esc(o.orderNumber)+"\">View</button><button class=\"btn light\" data-order-receipt=\""+esc(o.orderNumber)+"\">Receipt</button></div></td></tr>").join("");empty.hidden=list.length>0}
function edit(existing){const o=existing||{orderNumber:"TIF"+Date.now(),createdAt:new Date().toISOString(),customer:{name:"",phone:""},items:[{name:"",qty:1,price:0}],total:0,paymentMethod:"Bank transfer",paymentStatus:"Unpaid",status:"Pending",deliveryMethod:"Home delivery",deliveryAddress:""};const m=document.createElement("div");m.className="order-modal modal open";m.innerHTML="<div class=\"modalbox\"><div class=\"modalhead\"><h2>Order "+esc(o.orderNumber)+"</h2><button class=\"icon\" data-close>×</button></div><div class=\"formgrid\"><label>Customer name<input id=\"omName\" value=\""+esc(o.customer?.name)+"\"></label><label>Phone<input id=\"omPhone\" value=\""+esc(o.customer?.phone)+"\"></label><label>Delivery method<input id=\"omDelivery\" value=\""+esc(o.deliveryMethod||"Home delivery")+"\"></label><label>Delivery location<input id=\"omAddress\" value=\""+esc(o.deliveryAddress||"")+"\"></label><label>Payment<select id=\"omPayment\"><option>Bank transfer</option><option>Pay on delivery</option></select></label><label>Payment status<select id=\"omPayStatus\"><option>Unpaid</option><option>Pending verification</option><option>Paid</option><option>Refunded</option></select></label><label>Order status<select id=\"omStatus\"><option>Pending</option><option>Confirmed</option><option>Packed</option><option>Out for delivery</option><option>Delivered</option><option>Cancelled</option></select></label></div><h3>Items</h3><div id=\"omItems\" class=\"order-items\"></div><div class=\"actions\"><button id=\"omAdd\" class=\"btn light\">+ Item</button><button id=\"omSave\" class=\"btn primary\">Save order</button></div></div>";document.body.appendChild(m);
 const set=(id,v)=>{if(q(id))q(id).value=v||""};set("omPayment",o.paymentMethod||"Bank transfer");set("omPayStatus",o.paymentStatus||"Unpaid");set("omStatus",o.status||"Pending");
 function add(i){const r=document.createElement("div");r.className="order-item-row";r.innerHTML="<input class=\"oiName\" placeholder=\"Product\" value=\""+esc(i?.name||"")+"\"><input class=\"oiQty\" type=\"number\" min=\"1\" value=\""+(i?.qty||1)+"\"><input class=\"oiPrice\" type=\"number\" min=\"0\" step=\".01\" value=\""+(i?.price||0)+"\"><button type=\"button\" data-remove>×</button>";q("omItems").appendChild(r)}(o.items||[]).forEach(add);q("omAdd").onclick=()=>add({qty:1,price:0});q("omItems").onclick=e=>{if(e.target.matches("[data-remove]"))e.target.parentElement.remove()};
 q("omSave").onclick=()=>{const items=[...document.querySelectorAll(".order-modal .order-item-row")].map(r=>({name:r.querySelector(".oiName").value.trim(),qty:Number(r.querySelector(".oiQty").value||1),price:Number(r.querySelector(".oiPrice").value||0)})).filter(i=>i.name);const x={...o,customer:{name:q("omName").value.trim(),phone:q("omPhone").value.trim()},deliveryMethod:q("omDelivery").value.trim(),deliveryAddress:q("omAddress").value.trim(),paymentMethod:q("omPayment").value,paymentStatus:q("omPayStatus").value,status:q("omStatus").value,items,total:items.reduce((s,i)=>s+i.qty*i.price,0),updatedAt:new Date().toISOString()};const n=orders.findIndex(a=>a.orderNumber===x.orderNumber);n>=0?orders[n]=x:orders.unshift(x);save();m.remove();receipt(x)};q("omStatus").value=o.status||"Pending";q("omPayStatus").value=o.paymentStatus||"Unpaid";q("omPayment").value=o.paymentMethod||"Bank transfer";q("omName").focus();m.querySelector("[data-close]").onclick=()=>m.remove()}
function importOrder(){const raw=prompt("Paste customer order JSON here:");if(!raw)return;try{const o=JSON.parse(raw);if(!o.orderNumber||!Array.isArray(o.items))throw Error("Invalid order JSON");const n=orders.findIndex(x=>x.orderNumber===o.orderNumber);n>=0?orders[n]=o:orders.unshift(o);save();receipt(o)}catch(e){alert("Import failed: "+e.message)}}
function receipt(o){const w=window.open("","_blank");if(!w){alert("Please allow pop-ups for receipts.");return}w.document.write("<!doctype html><html><head><title>TIFFAS Receipt "+esc(o.orderNumber)+"</title><style>body{font-family:Arial;max-width:680px;margin:30px auto;color:#111}h1{text-align:center;font-size:22px}.meta{display:flex;justify-content:space-between;gap:20px;font-size:12px;margin:15px 0}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}.total{display:flex;justify-content:space-between;border-top:2px solid #111;margin-top:12px;padding-top:10px;font-weight:800}.note{text-align:center;font-size:11px;margin-top:22px}</style></head><body><h1>TIFFAS BEAUTY & COSMETICS</h1><p style=\"text-align:center\">Customer Receipt</p><div class=\"meta\"><div>Order: "+esc(o.orderNumber)+"<br>Date: "+new Date(o.createdAt||Date.now()).toLocaleString("en-KE")+"</div><div>Customer: "+esc(o.customer?.name||"—")+"<br>Phone: "+esc(o.customer?.phone||"—")+"</div></div><p><b>Delivery:</b> "+esc(o.deliveryMethod||"—")+" "+esc(o.deliveryAddress||"")+"</p><table><thead><tr><th>Item</th><th>Qty</th><th>Amount</th></tr></thead><tbody>"+(o.items||[]).map(i=>"<tr><td>"+esc(i.name)+(i.request?"<br><small>"+esc(i.request)+"</small>":"")+"</td><td>"+i.qty+"</td><td>"+money(i.qty*i.price)+"</td></tr>").join("")+"</tbody></table><div class=\"total\"><span>Total</span><span>"+money(o.total)+"</span></div><p>Payment: "+esc(o.paymentMethod||"—")+" • "+esc(o.paymentStatus||"Unpaid")+"</p><p class=\"note\">Thank you for shopping with TIFFAS BEAUTY & COSMETICS.</p><script>window.onload=()=>window.print()<\/script></body></html>");w.document.close()}
document.addEventListener("click",e=>{const v=e.target.closest("[data-order-view]"),r=e.target.closest("[data-order-receipt]");if(v){const o=orders.find(x=>x.orderNumber===v.dataset.orderView);if(o)edit(o)}if(r){const o=orders.find(x=>x.orderNumber===r.dataset.orderReceipt);if(o)receipt(o)}});
load();setTimeout(render,250);window.TIFFAS_ADMIN_ORDERS={get:()=>orders,save:save};
})();