const CACHE_NAME="tiffas-admin-v20";const DB_NAME="tiffas_admin_offline_v3",DB_STORE="state",SYNC_TAG="tiffas-admin-sync";const REPO="tiffasbeautyandcosmetics/Tiffasbeauty-cosmetics-store",API="https://api.github.com";
self.addEventListener("install",e=>{e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(["./","./index.html","./admin.js?v=20","./admin.css?v=20"])));self.skipWaiting();});
self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener("fetch",e=>{const u=new URL(e.request.url);if(e.request.method!=="GET"||u.origin!==self.location.origin)return; e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE_NAME).then(cache=>cache.put(e.request,copy)).catch(()=>{});return r;}).catch(()=>caches.match("./index.html"))));});
function dbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DB_STORE))r.result.createObjectStore(DB_STORE);};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error("Offline storage unavailable"));});}
async function dbGet(){const db=await dbOpen();return new Promise((resolve,reject)=>{const r=db.transaction(DB_STORE,"readonly").objectStore(DB_STORE).get("snapshot");r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);});}
async function dbPut(v){const db=await dbOpen();return new Promise((resolve,reject)=>{const r=db.transaction(DB_STORE,"readwrite").objectStore(DB_STORE).put(v,"snapshot");r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
function decode(b64){const bin=atob((b64||"").replace(/\n/g,""));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes);}
function encode(text){const bytes=new TextEncoder().encode(text);let bin="";bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin);}
async function gh(path,token,options={}){const r=await fetch(API+path,{...options,headers:{"Accept":"application/vnd.github+json","Authorization":"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28",...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"GitHub sync failed");return d;}
async function getFile(path,token){const d=await gh("/repos/"+REPO+"/contents/"+path+"?ref=main",token);return{content:decode(d.content),sha:d.sha};}
async function putFile(path,content,sha,message,token){return gh("/repos/"+REPO+"/contents/"+path,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,content:encode(content),sha,branch:"main"})},token);}
function slug(s){return String(s||"product").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"product";}
function dataUrlBlob(dataUrl){const parts=dataUrl.split(",");const m=(parts[0].match(/data:([^;]+);base64/)||[])[1]||"image/jpeg";const bin=atob(parts[1]||"");const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:m});}
async function uploadOfflineImage(dataUrl,name,settings,token){const blob=dataUrlBlob(dataUrl);const filename=slug(name)+"-offline-"+Date.now()+".jpg";if(settings.cloudinaryCloudName&&settings.cloudinaryUploadPreset){const form=new FormData();form.append("file",blob,filename);form.append("upload_preset",settings.cloudinaryUploadPreset);const cr=await fetch("https://api.cloudinary.com/v1_1/"+encodeURIComponent(settings.cloudinaryCloudName)+"/image/upload",{method:"POST",body:form});const d=await cr.json().catch(()=>({}));if(cr.ok&&d.secure_url)return{url:d.secure_url,cloudinaryUrl:d.secure_url};}
const ab=await blob.arrayBuffer(),bytes=new Uint8Array(ab);let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));await gh("/repos/"+REPO+"/contents/images/products/"+filename,token,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:"TIFFAS offline image backup: "+name,content:btoa(binary),branch:"main"})});return{url:"images/products/"+filename,cloudinaryUrl:""};}
async function syncNow(){const state=await dbGet();if(!state||!state.offlineDirty&&!state.settingsDirty)return;if(!state.token)return;const token=state.token;const latest=await getFile("catalog/products.json",token),remote=JSON.parse(latest.content),local=state.products||[],deleted=new Set(state.deletedIds||[]),localById=new Map(local.map(p=>[String(p.id),p])),merged=[];for(const p of remote){const id=String(p.id);if(deleted.has(id))continue;merged.push(localById.has(id)?localById.get(id):p);localById.delete(id);}for(const p of localById.values())merged.push(p);
for(const p of merged){if(typeof p.image==="string"&&p.image.startsWith("data:")){const up=await uploadOfflineImage(p.image,p.name,state.settings||{},token);p.image=up.url;if(up.cloudinaryUrl)p.cloudinaryImage=up.cloudinaryUrl;if(up.url!==up.cloudinaryUrl)p.fallbackImage=up.url;}}
await putFile("catalog/products.json",JSON.stringify(merged,null,2),latest.sha,"Sync offline TIFFAS catalogue changes",token);
if(state.settingsDirty){const sf=await getFile("store-settings.json",token);await putFile("store-settings.json",JSON.stringify(state.settings||{},null,2),sf.sha,"Sync offline TIFFAS store settings",token);}
await dbPut({...state,products:merged,deletedIds:[],offlineDirty:false,settingsDirty:false,updatedAt:new Date().toISOString()});
const clients=await self.clients.matchAll({includeUncontrolled:true});clients.forEach(c=>c.postMessage({type:"sync-complete"}));}
self.addEventListener("sync",e=>{if(e.tag===SYNC_TAG)e.waitUntil(syncNow().catch(()=>{}));});
